export const COMPANY_LIST = [
  { code: '1101', name: '台泥' },
  { code: '1216', name: '統一' },
  { code: '1301', name: '台塑' },
  { code: '1303', name: '南亞' },
  { code: '1326', name: '台化' },
  { code: '2002', name: '中鋼' },
  { code: '2207', name: '和泰車' },
  { code: '2301', name: '光寶科' },
  { code: '2303', name: '聯電' },
  { code: '2308', name: '台達電' },
  { code: '2317', name: '鴻海' },
  { code: '2327', name: '國巨' },
  { code: '2330', name: '台積電' },
  { code: '2345', name: '智邦' },
  { code: '2357', name: '華碩' },
  { code: '2379', name: '瑞昱' },
  { code: '2382', name: '廣達' },
  { code: '2395', name: '研華' },
  { code: '2412', name: '中華電' },
  { code: '2454', name: '聯發科' },
  { code: '2603', name: '長榮' },
  { code: '2880', name: '華南金' },
  { code: '2881', name: '富邦金' },
  { code: '2882', name: '國泰金' },
  { code: '2883', name: '凱基金' },
  { code: '2884', name: '玉山金' },
  { code: '2885', name: '元大金' },
  { code: '2886', name: '兆豐金' },
  { code: '2887', name: '台新金' },
  { code: '2890', name: '永豐金' },
  { code: '2891', name: '中信金' },
  { code: '2892', name: '第一金' },
  { code: '2912', name: '統一超' },
  { code: '3008', name: '大立光' },
  { code: '3017', name: '奇鋐' },
  { code: '3034', name: '聯詠' },
  { code: '3037', name: '欣興' },
  { code: '3045', name: '台灣大' },
  { code: '3231', name: '緯創' },
  { code: '4904', name: '遠傳' },
  { code: '6505', name: '台塑化' }
];

export const PREDICTION_FEATURES = [
  '年營業額成長比率', '公司現金流', '每股盈餘 EPS ', 
  '公司市值（同業比較）', '公司產業屬性（半導體…）', '機構大型投資比重', 
  '分析師評價（投顧研究報告書）', '市場輿情熱度', '氣候風險因子評級'
];


export const predplot = [
    { day: 1, 'Market Return Rate': 12.5, 'Market Return Rate Pred': null },
    { day: 2, 'Market Return Rate': 13.8, 'Market Return Rate Pred': null },
    { day: 3, 'Market Return Rate': 14.2, 'Market Return Rate Pred': null },
    { day: 4, 'Market Return Rate': 15.3, 'Market Return Rate Pred': null },
    { day: 5, 'Market Return Rate': 16.1, 'Market Return Rate Pred': null },
    { day: 6, 'Market Return Rate': 17.0, 'Market Return Rate Pred': null },
    { day: 7, 'Market Return Rate': 18.2, 'Market Return Rate Pred': null },
    { day: 8, 'Market Return Rate': 19.5, 'Market Return Rate Pred': null },
    { day: 9, 'Market Return Rate': 20.3, 'Market Return Rate Pred': null },
    { day: 10, 'Market Return Rate': 21.8, 'Market Return Rate Pred': null },
    { day: 11, 'Market Return Rate': 22.6, 'Market Return Rate Pred': null },
    { day: 12, 'Market Return Rate': 23.4, 'Market Return Rate Pred': null },
    { day: 13, 'Market Return Rate': 24.1, 'Market Return Rate Pred': null },
    { day: 14, 'Market Return Rate': 25.0, 'Market Return Rate Pred': null },
    { day: 15, 'Market Return Rate': 26.2, 'Market Return Rate Pred': null },
    { day: 16, 'Market Return Rate': 27.1, 'Market Return Rate Pred': null },
    { day: 17, 'Market Return Rate': 28.3, 'Market Return Rate Pred': null },
    { day: 18, 'Market Return Rate': 29.0, 'Market Return Rate Pred': null },
    { day: 19, 'Market Return Rate': 30.1, 'Market Return Rate Pred': null },
    { day: 20, 'Market Return Rate': 31.5, 'Market Return Rate Pred': null },
    { day: 21, 'Market Return Rate': 32.7, 'Market Return Rate Pred': null },
    { day: 22, 'Market Return Rate': 33.9, 'Market Return Rate Pred': null },
    { day: 23, 'Market Return Rate': 35.1, 'Market Return Rate Pred': null },
    { day: 24, 'Market Return Rate': 36.4, 'Market Return Rate Pred': null },
    { day: 25, 'Market Return Rate': 37.8, 'Market Return Rate Pred': null },
    { day: 26, 'Market Return Rate': 39.2, 'Market Return Rate Pred': 39.2},
    { day: 27, 'Market Return Rate': null, 'Market Return Rate Pred': 40.7},
    { day: 28, 'Market Return Rate': null, 'Market Return Rate Pred': 42.1},
    { day: 29, 'Market Return Rate': null, 'Market Return Rate Pred': 39.2},
    { day: 30, 'Market Return Rate': null, 'Market Return Rate Pred': 40.7},
  ];